### ISSUE TITLE
Suggestion in Attachment feature for Documents 

### ISSUE THREAD

**Issue by ShiyamPRO** [shiyamsabari01/WhatsappDevelopement#5]
Hi Sabari,

I suggest your project add a new feature in the Attachment section. Please add the Documents share option in your application

**Comment by shiyamsabari01** [comment]
Hi Shiyam,

Thank you for letting us know. we will be working on that feature. Once the feature is added, I will let you know. Keep support us

**Comment by shiyamsabari01** [comment]
Hi shiyam ,

We will developed Documents feature your issue #5 has been developed.Thanks
